#!/bin/sh

ret=0

# stash any unstaged changes to avoid testing unwanted code
stash_name="pre-commit-stash-$( date +%s )"
git stash save -q --keep-index ${stash_name}

# check if any of the files in server/ is modified
if git diff --cached --name-only | grep -qE "^server/" ; then

    # execute linting and tests
    (
        cd server
        grunt

    )
    ret=$?

fi

if [ $ret -ne 0 ]; then
    echo "Commit rejected."
fi
# restore stashed changes if any
if git stash list | grep -q ${stash_name} ; then
    git stash pop -q
fi

exit $ret
