#!/bin/sh

ret=0

# stash any unstaged changes to avoid testing unwanted code
git stash -q --keep-index pre-commit-stash

# check if any of the files in server/ is modified
if git diff --cached --name-only | grep -qE "^server/" ; then

    # execute linting and tests
    (
        cd server
        grunt

    )
    ret=$?

fi

if [ $ret -ne 0 ]; then
    echo "Commit rejected."
fi
# restore stashed changes
git stash pop -q

exit $ret
