# Copyright(c) 2016 Bitergia
# MIT Licensed

FROM busybox
MAINTAINER Bitergia <fiware-testing@bitergia.com>

ADD https://raw.githubusercontent.com/Bitergia/docker/master/utils/entrypoint-common.sh /tourguide/common/entrypoint-common.sh
COPY pep-wilma /tourguide/pep-wilma

